name: CI - Test & Coverage Enforcement on Feature Branch

on:
  push:
    branches:
        - main 
        - feature/*
  pull_request:
    branches: [feature/*]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with 100% Coverage Enforcement
        run: |
          PYTHONPATH=. pytest --cov=app --cov=ml_model tests/ --cov-report xml --cov-fail-under=100

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >            
            -Dsonar.organization=jmreddy2106
            -Dsonar.projectKey=ml-flask-app
            -Dsonar.sources=.
            -Dsonar.language=py
            -Dsonar.tests=tests
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -X 